fix: testing pipeline fix on .env fernet key being bad and tests not running

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,6 +17,8 @@ variables:
 default:
   tags:
     - docker-gcc
+  before_script:
+    - set -ex
 
 .backend-base:
   image: ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-${BASE_LAYER}
@@ -45,8 +47,8 @@ uv-install:
     paths:
       - ${UV_CACHE_DIR}
     policy: pull-push
-  script: |
-    uv cache prune --ci
+  script: 
+    - uv cache prune --ci
 
 sync_lock:
   stage: sync_lock
@@ -63,7 +65,6 @@ lint:
   stage: lint
   extends: .backend-base
   script: |
-    set -ex
     uvx ruff check --fix .
     uvx ruff format .
   needs:
@@ -75,11 +76,15 @@ test:
   services:
     - name: redis:7.0.11-alpine
       alias: redis
-  script: |
-    set -ex 
+  script: | 
     apt-get update -qq && apt-get install -y redis-tools
     redis-cli -h $REDIS_HOST -p $REDIS_PORT ping
     uv run python -m scripts.create_env
+    if [ ! -f ".env" ]; then
+      echo "Test Failed: .env file was not generated" 
+      exit 1
+    fi
+    export $(grep -v '^#' .env | xargs -d '\n')
     uv run api conf set test
     uv run pytest -v ./tests --disable-warnings --cov=app --cov-report=html
   needs:
